### PR TITLE
core: fix oauth user register & bind (#632)

### LINKED ISSUE #632: 关于 GitHub OAuth 登录的逻辑问题
事情的起因是这样的，我之前给我 GitHub 账号更换了 public email，然后重新登录 Hydro 的时候它重新给我开了个号。

翻了一下 GitHub OAuth 插件的实现，发现用的是 email 作为用户标识符。（这个算是普遍现象了，听说之前有家知名 VPS 商也有这个问题）

我的个人建议是使用 GitHub 的用户 id 作为用户的唯一标识符。要不然很容易出事。

### PR DESCRIPTION
**Pull request by pandadtdyy**
fix #632.

### CODE REVIEW

File: packages/hydrooj/src/handler/user.ts [hunk 1]
```diff
@@ -466,6 +466,7 @@ class OauthCallbackHandler extends Handler {
             if (r.email) {
                 const udoc = await user.getByEmail('system', r.email);
                 if (udoc) {
+                    await oauth.set(r._id, udoc._id);
```
Comment (undefined-moe) [inline packages/hydrooj/src/handler/user.ts:469]: The source id should be platform related.

**Review by undefined-moe — CHANGES_REQUESTED** [review]

**Review by undefined-moe — APPROVED** [review]
